version: "3.7"

services:
  plex:
    image: linuxserver/plex:latest 
    container_name: plex
    expose:
      - 32400
      - 33400
    ports:
      - 32400:32400
      - 33400:33400
    environment:
      - TZ=Europe/Madrid
      # Solo aplica si lo estas montando fuera de tu red local, osea en un servidor remoto
      # - PLEX_CLAIM=claim-xxxxxx # TODO: https://www.plex.tv/claim/ 
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    networks:
      - plex_network

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./sonarr:/config
      - ${MEDIA}:/tv:rw
      - ${STORAGE}/downloads:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - plex_network
  
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./radarr:/config
      - ${MEDIA}:/movies:rw
      - ${STORAGE}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - plex_network

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config
      - ${STORAGE}/downloads:/downloads:rw
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - plex_network

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true
    volumes:
      - ./jackett:/config
      - ${STORAGE}/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - plex_network

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=m
      - SERVER_COUNTRIES=USA
      - TZ=Europe/Madrid
    volumes:
      - ./gluetun:/gluetun
    ports:
      - 8081:8081
      - 9117:9117
    restart: unless-stopped
    networks:
      - plex_network


networks:
  plex_network:
    driver: bridge