version: "3.7"

services:
  plex:
    image: linuxserver/plex:latest 
    container_name: plex
    expose:
      - 32400
      - 33400
    ports:
      - 32400:32400
      - 33400:33400
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    networks:
      - plex_network

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./sonarr:/config
      - ${MEDIA}:/tv 
      - ${STORAGE}/downloads:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - plex_network
  
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./radarr:/config
      - ${MEDIA}:/movies 
      - ${STORAGE}/downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - plex_network

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config
      - ${STORAGE}/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - plex_network

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - AUTO_UPDATE=true
    volumes:
      - ./jackett:/config
      - ${STORAGE}/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - plex_network

networks:
  plex_network:
    driver: bridge