version: "3.7"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=123456789012  # Reemplazar con tu número de cuenta Mullvad
      - OPENVPN_PASSWORD=m
      - SERVER_COUNTRIES=Sweden     # Cambialo si querés otro país
      - TZ=Europe/Madrid
    volumes:
      - ./gluetun:/gluetun
    ports:
      - 8081:8081     # qBittorrent
      - 9117:9117     # Jackett
      - 7878:7878     # Radarr
      - 8989:8989     # Sonarr
    restart: unless-stopped
    networks:
      - plex_network

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config
      - ${STORAGE}/downloads:/downloads:rw
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true
    volumes:
      - ./jackett:/config
      - ${STORAGE}/downloads:/downloads
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./sonarr:/config
      - ${MEDIA}:/tv:rw
      - ${STORAGE}/downloads:/downloads
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./radarr:/config
      - ${MEDIA}:/movies:rw
      - ${STORAGE}/downloads:/downloads
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./bazarr:/config
      - ${MEDIA}:/tv
      - ${MEDIA}:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - plex_network

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    expose:
      - 32400
      - 33400
    ports:
      - 32400:32400
      - 33400:33400
    environment:
      - TZ=Europe/Madrid
      # - PLEX_CLAIM=claim-xxxxxx
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    networks:
      - plex_network

networks:
  plex_network:
    driver: bridge
